version: "3"

networks:
  backend:

services:
  database:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    tty: true
    environment:
      - POSTGRES_DB=Base
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    tty: true
    volumes:
      - .:/code/
    working_dir: /code/
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.8.16
    depends_on:
      - django
